name: Auto Version Bump

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'constants.py'  # Prevent infinite loop when we update constants.py

permissions:
  contents: write

jobs:
  version-bump:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Extract current version and increment patch
      id: version
      run: |
        # Read current version from constants.py
        current_version=$(grep "SERVER_VERSION = " constants.py | sed 's/SERVER_VERSION = "//' | sed 's/"//')
        echo "Current version: $current_version"
        
        # Split version into parts
        IFS='.' read -r major minor patch <<< "$current_version"
        
        # Increment patch version
        new_patch=$((patch + 1))
        new_version="$major.$minor.$new_patch"
        
        echo "New version: $new_version"
        echo "new_version=$new_version" >> $GITHUB_OUTPUT

    - name: Update version in constants.py
      run: |
        new_version="${{ steps.version.outputs.new_version }}"
        # Use sed to replace the SERVER_VERSION line
        sed -i "s/SERVER_VERSION = \".*\"/SERVER_VERSION = \"$new_version\"/" constants.py
        
        # Verify the change
        echo "Updated constants.py:"
        grep "SERVER_VERSION = " constants.py

    - name: Commit and push version bump
      run: |
        git add constants.py
        git commit -m "bump version to ${{ steps.version.outputs.new_version }}"
        git push
